apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-db-ebs
  namespace: shop
  labels:
    app: shop
    tier: db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 5Gi
