apiVersion: v1
kind: Service
metadata:
  name: shop-web
  namespace: shop
  labels:
    app: shop
    tier: web
spec:
  type: NodePort
  selector:
    app: shop
    tier: web
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
