apiVersion: v1
kind: PersistentVolume
metadata:
  name: shop-share-pv
  labels:
    app: shop
    tier: share
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    server: 10.20.1.10
    path: /srv/nfs/shop-share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-share
  namespace: shop
  labels:
    app: shop
    tier: share
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: shop-share-pv
  resources:
    requests:
      storage: 1Gi
