apiVersion: v1
kind: Pod
metadata:
  name: __NAME__
  namespace: shop
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: __NODE__
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "db"
      effect: "NoSchedule"
  containers:
    - name: writer
      image: busybox:1.37
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      command: ["sh", "-c", "echo \"$(hostname) on $NODE_NAME\" >> /data/visits.txt; cat /data/visits.txt"]
      volumeMounts:
        - name: host-dir
          mountPath: /data
  volumes:
    - name: host-dir
      hostPath:
        path: /tmp/lab11-hostpath
        type: DirectoryOrCreate
