apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab11-retain-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    server: 10.20.1.10
    path: /srv/nfs/shop-share/lab11-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab11-retain
  namespace: shop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: lab11-retain-pv
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: lab11-retain-writer
  namespace: shop
spec:
  restartPolicy: Never
  nodeSelector:
    tier: front
  containers:
    - name: writer
      image: busybox:1.37
      command: ["sh", "-c", "echo keep-me > /data/keep.txt && cat /data/keep.txt"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: lab11-retain
