apiVersion: v1
kind: Pod
metadata:
  name: lab11-emptydir
  namespace: shop
spec:
  nodeSelector:
    tier: front
  containers:
    - name: writer
      image: busybox:1.37
      command: ["sh", "-c", "trap 'exit 0' TERM; while true; do date +%T >> /cache/log.txt; sleep 5; done"]
      volumeMounts:
        - name: cache
          mountPath: /cache
    - name: reader
      image: busybox:1.37
      command: ["sh", "-c", "touch /cache/log.txt; tail -F /cache/log.txt"]
      volumeMounts:
        - name: cache
          mountPath: /cache
  volumes:
    - name: cache
      emptyDir: {}
